name: Go Check

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'vscext/**'
      - '.github/workflows/vscext-check.yml'      
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'vscext/**'
      - '.github/workflows/vscext-check.yml'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    - run: go build ./mcpgo/mcp.go
    - run: go test ./...